server:
  port: 11000
spring:
  application:
    name: SCW-WEBUI
  session:
    store-type: redis
  redis:
    host: localhost
    port: 6379



  thymeleaf:
    prefix: classpath:/templates/
    suffix: .html
    cache: false #开发的时候禁用缓存



feign:
  hystrix:
    enabled: true

eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka/
  instance:
    appname: SCW-WEBUI
    prefer-ip-address: true
ribbon:
  ReadTimeout: 3000
  ConnectTimeout: 3000
  MaxAutoRetries: 0
  MaxAutoRetryiesNextServer: 0
  OkToRetryOnAllOperations: false




