spring:
  datasource:
    username: root
    password: root
    url: jdbc:mysql://localhost:3306/atcrowdfunding?useSSL=false&useUnicode=true&characterEncoding=UTF-8&serverTimezone=UTC&allowPublicKeyRetrieval=true
    driver-class-name: com.mysql.cj.jdbc.Driver
  #    type: com.alibaba.druid.pool.DruidDataSource
  #    filters: stat
  application:
    name: SCW-USER
  redis:
    host: localhost
    port: 6379



mybatis:
  config-location: classpath:/mybatis/mybatis-config.xml
  mapper-locations: classpath:/mybatis/mapper/*.xml

eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka/
  instance:
    appname: SCW-USER
    prefer-ip-address: true

server:
  port: 7000
