spring:
  datasource:
    username: root
    password: root
    url: jdbc:mysql://localhost:3306/atcrowdfunding?useSSL=false&useUnicode=true&characterEncoding=UTF-8&serverTimezone=UTC&allowPublicKeyRetrieval=true
    driver-class-name: com.mysql.cj.jdbc.Driver
  application:
    name: SCW-ORDER 
  redis:
    host: localhost
    port: 6379

feign:
  hystrix:
    enabled: true
    
mybatis:
  config-location: classpath:/mybatis/mybatis-config.xml
  mapper-locations: classpath:/mybatis/mapper/*.xml
  
  
eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka/
  instance:
    #appname: ORDER
    prefer-ip-address: true
    
    
server:
  port: 9200


Swagger:
  enable: true
  

    
  